name: Deploy VitePress site to Pages and Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build modern version for GitHub Pages
  build-modern:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Modern Version
        run: |
          npm run build:modern
          touch src/modern/.vitepress/dist/.nojekyll
      - name: Debug Build Output
        run: |
          echo "Checking dist folder for modern build"
          ls -R src/modern/.vitepress/dist || echo "Modern build output directory not found"
      - name: Upload Modern Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/modern/.vitepress/dist

  # Deploy modern version to GitHub Pages
  deploy-modern:
    environment:
      name: github-pages
      url: https://support.mantishub.com
    needs: build-modern
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Modern to GitHub Pages
        id: deployment-modern
        uses: actions/deploy-pages@v4

  deploy-to-server:
    needs: build-modern
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Debug Directories
        run: |
          ls -R src/modern || echo "src/modern directory not found"
          ls -R src/classic || echo "src/classic directory not found"

      - name: Build Modern and Classic Versions
        run: |
          npm run build:modern
          npm run build:classic

      - name: Debug Build Outputs
        run: |
          ls -R src/modern/.vitepress/dist || echo "Modern build output directory not found"
          ls -R src/classic/.vitepress/dist || echo "Classic build output directory not found"

      - name: Set up SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keygen -F ${{ vars.SERVER_IP }} > /dev/null; then
            ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
          fi
          chmod 600 ~/.ssh/known_hosts

      - name: Create Modern Directory
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern && sudo chown -R forge:forge /var/www/modern"

      - name: Create Classic Directory
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/classic && sudo chown -R forge:forge /var/www/classic"

      - name: Deploy Modern Files
        run: |
          if [ -d "src/modern/.vitepress/dist" ]; then
            rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/modern/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/
          else
            echo "Modern build output directory missing. Skipping deployment."
            exit 1
          fi

      - name: Deploy Classic Files
        run: |
          if [ -d "src/classic/.vitepress/dist" ]; then
            rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/classic/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/
          else
            echo "Classic build output directory missing. Skipping deployment."
            exit 1
          fi

      - name: Configure Nginx
        run: |
          ssh -tt forge@${{ vars.SERVER_IP }} << 'EOF'
          cat << CONFIG > /tmp/nginx_config
          server {
              server_name modern.mantishub.com;
              root /var/www/modern;

              index index.html;

              location / {
                  try_files \$uri \$uri/ =404;
              }

              listen 80;
          }

          server {
              server_name classic.mantishub.com;
              root /var/www/classic;

              index index.html;

              location / {
                  try_files \$uri \$uri/ =404;
              }

              listen 80;
          }
          CONFIG

          sudo mv /tmp/nginx_config /etc/nginx/sites-available/combined.conf
          sudo ln -sf /etc/nginx/sites-available/combined.conf /etc/nginx/sites-enabled/

          if sudo nginx -t; then
            sudo systemctl reload nginx
          else
            echo "Nginx configuration test failed."
            exit 1
          fi
          EOF

      - name: Install SSL Certificates
        run: |
          ssh -tt forge@${{ vars.SERVER_IP }} << 'EOF'
          sudo apt-get update
          if ! command -v certbot &> /dev/null; then
            sudo apt-get install -y certbot python3-certbot-nginx
          fi
          sudo certbot --nginx -d modern.mantishub.com --non-interactive --agree-tos -m arundevops47@gmail.com
          sudo certbot --nginx -d classic.mantishub.com --non-interactive --agree-tos -m arundevops47@gmail.com
          EOF

      - name: Verify SSL Renewal
        run: |
          ssh -tt forge@${{ vars.SERVER_IP }} << 'EOF'
          sudo certbot renew --dry-run
          EOF
