name: Deploy VitePress site to Pages and Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # Set up SSH for Server Deployment
      - name: Set up SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      # Add Server to Known Hosts
      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keyscan -H ${vars.SERVER_IP} >> ~/.ssh/known_hosts; then
            echo "Failed to add server to known hosts"
          fi
          chmod 600 ~/.ssh/known_hosts

      # Build Classic
      - name: Build Classic
        run: npm run build:classic

      - name: Create Classic Directory on Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/classic && sudo chown -R forge:forge /var/www"

      # rsync Classic to Server
      - name: Deploy Classic Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/classic/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/

      # Build Modern
      - name: Build Modern
        run: npm run build:modern

      - name: Create Modern Directory on Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern && sudo chown -R forge:forge /var/www"

      # rsync Modern to Server
      - name: Deploy Modern Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/modern/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/

      # Publish Modern to GitHub Pages by pushing to gh-pages branch
      - name: Configure Git for Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy Modern to GitHub Pages
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp -R src/modern/.vitepress/dist/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy modern site" || true
          git push origin gh-pages --force