name: Deploy VitePress site to Pages and Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # Build Classic
      - name: Build Classic Version
        run: npm run build:classic

      - name: Upload Classic Artifact for Server
        uses: actions/upload-artifact@v4
        with:
          name: classic-build
          path: src/classic/.vitepress/dist

      # Build Modern
      - name: Build Modern Version
        run: |
          npm run build:modern
          touch src/modern/.vitepress/dist/.nojekyll

      # Upload Artifacts
      - name: Upload Modern Artifact for Server
        uses: actions/upload-artifact@v4
        with:
          name: modern-build
          path: src/modern/.vitepress/dist

      # Upload Pages Artifact
      - name: Upload Pages Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: src/modern/.vitepress/dist

  deploy-server:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts; then
            echo "Failed to add server to known hosts"
          fi
          chmod 600 ~/.ssh/known_hosts

      - name: Download Modern Artifact
        uses: actions/download-artifact@v4
        with:
          name: modern-build
          path: modern-dist

      - name: Download Classic Artifact
        uses: actions/download-artifact@v4
        with:
          name: classic-build
          path: classic-dist

      - name: Create Deployment Directories on Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern /var/www/classic && sudo chown -R forge:forge /var/www"

      - name: Deploy Modern Files to Server
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete modern-dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/

      - name: Deploy Classic Files to Server
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete classic-dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://support.mantishub.com
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
