name: Deploy VitePress Site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Modern and Classic Versions
        run: |
          npm run build:modern
          npm run build:classic
      - name: Debug Build Outputs
        run: |
          ls -R src/modern/.vitepress/dist || echo "Modern build output directory not found"
          ls -R src/classic/.vitepress/dist || echo "Classic build output directory not found"
      - name: Upload Modern Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/modern/.vitepress/dist

  deploy-modern:
    needs: build
    environment:
      name: github-pages
      url: https://support.mantishub.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Modern to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-server:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keygen -F ${{ vars.SERVER_IP }} > /dev/null; then
            ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
          fi
          chmod 600 ~/.ssh/known_hosts
      - name: Create Directories on Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern /var/www/classic && sudo chown -R forge:forge /var/www"
      - name: Deploy Modern Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/modern/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/
      - name: Deploy Classic Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/classic/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/
