name: Deploy VitePress Site to Pages and Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build classic and modern versions
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Classic Version
        run: |
          npm run build:classic
          touch src/classic/.vitepress/dist/.nojekyll
      - name: Build Modern Version
        run: |
          npm run build:modern
          touch src/modern/.vitepress/dist/.nojekyll

  # Rsync Classic and Modern Versions to Server
  deploy-to-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keygen -F ${{ vars.SERVER_IP }} > /dev/null; then
            ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
          fi
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy Classic Files to Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/classic && sudo chown -R forge:forge /var/www/classic"
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/classic/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/

      - name: Deploy Modern Files to Server
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern && sudo chown -R forge:forge /var/www/modern"
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/modern/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/

  # Publish Modern Version to GitHub Pages
  deploy-modern-to-pages:
    needs: build
    environment:
      name: github-pages
      url: https://support.mantishub.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Modern to GitHub Pages
        id: deployment-modern
        uses: actions/deploy-pages@v4
        with:
          path: src/modern/.vitepress/dist