name: Deploy VitePress site to Pages and Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Modern Version
        run: |
          npm run build:modern
          touch src/modern/.vitepress/dist/.nojekyll
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: src/modern/.vitepress/dist
      - name: Build Classic Version
        run: npm run build:classic
      - name: Upload Modern Artifact for Server
        uses: actions/upload-artifact@v4
        with:
          name: modern-build
          path: src/modern/.vitepress/dist
      - name: Upload Classic Artifact for Server
        uses: actions/upload-artifact@v4
        with:
          name: classic-build
          path: src/classic/.vitepress/dist

  deploy-pages:
    environment:
      name: github-pages
      url: https://support.mantishub.com
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-server:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download Modern Artifact
        uses: actions/download-artifact@v4
        with:
          name: modern-build
          path: modern-dist
      - name: Download Classic Artifact
        uses: actions/download-artifact@v4
        with:
          name: classic-build
          path: classic-dist
      - name: Set up SSH Key and Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - name: Add Server to Known Hosts
        run: |
          if ! ssh-keygen -F ${{ vars.SERVER_IP }} > /dev/null; then
            ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
          fi
          chmod 600 ~/.ssh/known_hosts
      - name: Create Deployment Directories
        run: |
          ssh forge@${{ vars.SERVER_IP }} "sudo mkdir -p /var/www/modern /var/www/classic && sudo chown -R forge:forge /var/www"
      - name: Deploy Modern Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete modern-dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/
      - name: Deploy Classic Files
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete classic-dist/ forge@${{ vars.SERVER_IP }}:/var/www/classic/